import json
from pathlib import Path
from typing import List


# =========================
# CONFIGURATION
# =========================

PROJECT_ROOT = Path(__file__).resolve().parent.parent
INPUT_DIR = PROJECT_ROOT / "ingestion_outputs"
OUTPUT_DIR = PROJECT_ROOT / "ingestion_outputs"

OUTPUT_DIR.mkdir(exist_ok=True)


# =========================
# CORE FUNCTION
# =========================

def split_by_page_markers(full_text: str) -> List[dict]:
    """
    Splits extracted text into page-level chunks using explicit
    PAGE START / END markers.

    Returns:
    [
      {
        "page_number": 1,
        "text": "page text..."
      }
    ]
    """

    pages = []
    current_page_lines = []
    current_page_number = None

    for line in full_text.splitlines():

        # Detect page start
        if line.startswith("<<<PAGE") and "START>>>" in line:
            # Flush previous page
            if current_page_number is not None:
                pages.append({
                    "page_number": current_page_number,
                    "text": "\n".join(current_page_lines).strip()
                })
                current_page_lines = []

            # Extract page number safely
            try:
                current_page_number = int(line.split()[1])
            except (IndexError, ValueError):
                current_page_number = None

            continue

        # Detect page end (ignore marker)
        if line.startswith("<<<PAGE") and "END>>>" in line:
            continue

        # Accumulate page content
        if current_page_number is not None:
            current_page_lines.append(line)

    # Flush final page
    if current_page_number is not None and current_page_lines:
        pages.append({
            "page_number": current_page_number,
            "text": "\n".join(current_page_lines).strip()
        })

    return pages


# =========================
# PIPELINE FUNCTION
# =========================

def run_page_chunker(extracted_txt_path: Path):
    """
    Reads page-aware extracted text file and writes page-wise JSON.
    """

    if not extracted_txt_path.exists():
        raise FileNotFoundError(f"Extracted text file not found: {extracted_txt_path}")

    print(f"[INFO] Chunking pages for: {extracted_txt_path.name}")

    with open(extracted_txt_path, "r", encoding="utf-8") as f:
        full_text = f.read()

    pages = split_by_page_markers(full_text)

    output_file_name = extracted_txt_path.stem.replace("_extracted", "") + "_pages.json"
    output_path = OUTPUT_DIR / output_file_name

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "source_file": extracted_txt_path.name,
                "num_pages": len(pages),
                "pages": pages
            },
            f,
            indent=2,
            ensure_ascii=False
        )

    print(f"[SUCCESS] Page chunks saved to: {output_path}")
    print(f"[INFO] Total pages extracted: {len(pages)}")


# =========================
# MAIN EXECUTION
# =========================

if __name__ == "__main__":
    """
    Provide the extracted text file generated by text_extractor.py
    """

    EXTRACTED_TEXT_FILE = INPUT_DIR / "paper1_extracted.txt"
    run_page_chunker(EXTRACTED_TEXT_FILE)
